import { readFile, writeFile } from 'node:fs/promises'

const path = 'firestore.rules'
const block = (...lines) => lines.join('\n')
let source = await readFile(path, 'utf8')

function replaceOnce(before, after) {
  const count = source.split(before).length - 1
  if (count !== 1) throw new Error(`${path}: expected exactly one guarded match, found ${count}`)
  source = source.replace(before, after)
}

replaceOnce(
  "        && resource.data.get('invoice_record_count', -1) == 0\n        && resource.data.get('shipment_record_count', -1) == 0;",
  "        && resource.data.get('shipment_record_count', -1) == 0;",
)

replaceOnce(
  block(
    '    function onlyInvoiceStatusChanged() {',
    '      return onlyChanged([',
    "        'invoice_status',",
    "        'updated_at'",
    '      ]);',
    '    }',
  ),
  block(
    '    function onlyInvoiceStatusChanged() {',
    '      return onlyChanged([',
    "        'invoice_status',",
    "        'updated_at'",
    '      ]);',
    '    }',
    '',
    '    function saleInvoiceStatusValue(value) {',
    "      return value is string && value in ['Không xuất', 'Yêu cầu xuất'];",
    '    }',
    '',
    '    function saleMutableInvoiceStatusValue(value) {',
    "      return value is string && value in ['Không xuất', 'Yêu cầu xuất', 'Khách lẻ', 'HĐ nháp'];",
    '    }',
    '',
    '    function accountingInvoiceStatusValue(value) {',
    "      return value is string && value in ['Không xuất', 'Yêu cầu xuất', 'Đã xuất'];",
    '    }',
    '',
    '    function invoiceAmountValid(data) {',
    "      let amount = data.get('invoice_amount', 0);",
    '      return amount is number && amount >= 0;',
    '    }',
    '',
    '    function issuedInvoiceFieldsValid(data) {',
    "      return data.get('invoice_status', '') != 'Đã xuất'",
    '        || (',
    "          validBoundedString(data.get('invoice_number', ''), 1, 200)",
    "          && validBoundedString(data.get('invoice_date', ''), 1, 40)",
    '        );',
    '    }',
    '',
    '    function autoInvoiceCreateFromNewOrderAllowed(invoiceId) {',
    "      let orderId = request.resource.data.get('order_id', '');",
    '      let path = orderPath(orderId);',
    '      let order = getAfter(path).data;',
    '      return hasPerm(\'orders.create\')',
    '        && orderId is string',
    "        && orderId != ''",
    '        && !exists(path)',
    '        && existsAfter(path)',
    '        && orderDataIsActive(order)',
    '        && ownsOrderData(order)',
    "        && ownEmailField(order, 'created_by')",
    "        && request.resource.data.get('id', '') == invoiceId",
    "        && request.resource.data.get('order_code', '') == order.get('order_code', '')",
    "        && request.resource.data.get('created_by', '').lower() == email()",
    '        && requestMatchesOrderData(order)',
    "        && request.resource.data.get('invoice_number', '') == ''",
    "        && request.resource.data.get('invoice_date', '') == ''",
    "        && saleInvoiceStatusValue(request.resource.data.get('invoice_status', ''))",
    "        && request.resource.data.get('invoice_status', '') == order.get('invoice_status', '')",
    '        && invoiceAmountValid(request.resource.data)',
    "        && request.resource.data.get('invoice_amount', -1) == order.get('payable_amount', -2)",
    "        && request.resource.data.get('relation_revision', -1) == 1",
    "        && request.resource.data.get('last_operation_id', '') == order.get('last_operation_id', '')",
    "        && request.resource.data.get('status', '') == 'active'",
    "        && request.resource.data.get('active', false) == true",
    "        && request.resource.data.get('deleted', true) == false",
    "        && request.resource.data.get('created_at', null) == request.time",
    "        && request.resource.data.get('updated_at', null) == request.time",
    "        && order.get('invoice_record_count', -1) == 1",
    "        && order.get('invoice_relation_revision', -1) == 1",
    "        && order.get('relation_lock_version', 0) == 1",
    "        && relationMetadataMatches(order, 'invoices', 'create', invoiceId)",
    "        && order.get('relation_updated_at', null) == request.time;",
    '    }',
    '',
    '    function invoiceAccountingUpdateValid(orderId) {',
    '      let path = orderPath(orderId);',
    '      return accountingInvoiceStatusValue(request.resource.data.get(\'invoice_status\', \'\'))',
    '        && invoiceAmountValid(request.resource.data)',
    '        && issuedInvoiceFieldsValid(request.resource.data)',
    "        && request.resource.data.get('id', '') == resource.data.get('id', '')",
    "        && request.resource.data.get('relation_revision', -1) == resource.data.get('relation_revision', 0) + 1",
    '        && existsAfter(path)',
    "        && getAfter(path).data.get('invoice_status', '') == request.resource.data.get('invoice_status', '');",
    '    }',
    '',
    '    function saleInvoiceStatusUpdateAllowed(invoiceId) {',
    "      let orderId = resource.data.get('order_id', '');",
    '      let path = orderPath(orderId);',
    '      let order = get(path).data;',
    '      let after = getAfter(path).data;',
    '      return hasPerm(\'orders.edit\')',
    '        && orderId is string',
    "        && orderId != ''",
    '        && exists(path)',
    '        && existsAfter(path)',
    '        && orderDataIsActive(order)',
    "        && (ownsOrderData(order) || hasPerm('orders.view_all') || isAdmin())",
    "        && request.resource.data.get('order_id', '') == orderId",
    '        && childIdentityUnchanged()',
    '        && childOwnershipSafe(orderId)',
    '        && onlyChanged([',
    "          'invoice_status', 'relation_revision', 'last_operation_id', 'updated_at'",
    '        ])',
    "        && saleMutableInvoiceStatusValue(resource.data.get('invoice_status', ''))",
    "        && saleInvoiceStatusValue(request.resource.data.get('invoice_status', ''))",
    "        && request.resource.data.get('invoice_status', '') != resource.data.get('invoice_status', '')",
    "        && request.resource.data.get('relation_revision', -1) == resource.data.get('relation_revision', 0) + 1",
    "        && request.resource.data.get('relation_revision', -1) == after.get('invoice_relation_revision', -2)",
    "        && validBoundedString(request.resource.data.get('last_operation_id', ''), 1, 200)",
    "        && request.resource.data.get('last_operation_id', '') == after.get('last_operation_id', '')",
    "        && request.resource.data.get('updated_at', null) == request.time",
    "        && after.get('invoice_status', '') == request.resource.data.get('invoice_status', '')",
    "        && relationParentMarkerMatches(orderId, 'invoices', 'update', invoiceId, 'invoice_relation_revision');",
    '    }',
    '',
    '    function orderEditKeepsNonInvoiceSystemFields() {',
    '      return unchanged([',
    "          'paid_amount', 'debt_amount', 'computed_payment_status', 'payment_status',",
    "          'payment_count', 'deposit_count', 'collect_count',",
    "          'warehouse_fulfillment_status', 'warehouse_request_status',",
    "          'printing_progress_count', 'printing_lock_version', 'printing_last_action',",
    "          'printing_last_print_order_id', 'printing_lock_updated_by', 'printing_lock_updated_at',",
    "          'relation_lock_version', 'payment_record_count', 'invoice_record_count',",
    "          'shipment_record_count', 'payment_relation_revision', 'shipment_relation_revision',",
    "          'shipment_status', 'shipping_fee_total', 'cod_amount_total',",
    "          'deleted', 'active', 'status', 'deleted_at'",
    '        ]);',
    '    }',
    '',
    '    function orderSaleInvoiceStatusUpdateAllowed(orderId) {',
    "      let documentId = request.resource.data.get('relation_last_document_id', '');",
    '      let childPath = invoicePath(documentId);',
    '      return hasPerm(\'orders.edit\')',
    "        && (ownsOrderData(resource.data) || hasPerm('orders.view_all') || isAdmin())",
    '        && orderIdentityUnchanged()',
    '        && orderEditKeepsNonInvoiceSystemFields()',
    "        && fulfillmentStatus() != 'da_xuat_du'",
    "        && saleMutableInvoiceStatusValue(resource.data.get('invoice_status', ''))",
    "        && saleInvoiceStatusValue(request.resource.data.get('invoice_status', ''))",
    "        && request.resource.data.get('invoice_status', '') != resource.data.get('invoice_status', '')",
    "        && resource.data.get('invoice_record_count', -1) == 1",
    "        && request.resource.data.get('invoice_record_count', -1) == 1",
    "        && request.resource.data.get('revision', -1) == resource.data.get('revision', 0) + 1",
    "        && validBoundedString(request.resource.data.get('last_operation_id', ''), 1, 200)",
    '        && relationParentTransitionMatches(',
    "          orderId, childPath, 'invoices', 'update', documentId,",
    "          'invoice_record_count', 'invoice_relation_revision'",
    '        )',
    '        && exists(childPath)',
    '        && existsAfter(childPath)',
    "        && get(childPath).data.get('invoice_status', '') == resource.data.get('invoice_status', '')",
    "        && getAfter(childPath).data.get('invoice_status', '') == request.resource.data.get('invoice_status', '');",
    '    }',
    '',
    '    function invoiceOrderCascadeDeleteAllowed() {',
    "      let orderId = resource.data.get('order_id', '');",
    '      let path = orderPath(orderId);',
    '      return hasPerm(\'orders.delete\')',
    '        && orderId is string',
    "        && orderId != ''",
    '        && exists(path)',
    '        && existsAfter(path)',
    '        && orderDataIsActive(get(path).data)',
    "        && (ownsOrderData(get(path).data) || hasPerm('orders.view_all') || isAdmin())",
    '        && softDeleteOnly()',
    "        && getAfter(path).data.get('deleted', false) == true",
    "        && getAfter(path).data.get('active', true) == false;",
    '    }',
  ),
)

replaceOnce(
  block(
    "                request.resource.data.get('relation_last_module', '') == 'invoices'",
    '                && orderInvoiceSummaryUpdateAllowed(docId)',
  ),
  block(
    "                request.resource.data.get('relation_last_module', '') == 'invoices'",
    '                && (',
    '                  orderInvoiceSummaryUpdateAllowed(docId)',
    '                  || orderSaleInvoiceStatusUpdateAllowed(docId)',
    '                )',
  ),
)

replaceOnce(
  block(
    '    match /invoices/{docId} {',
    '      allow read: if isAdmin()',
    "        || hasPerm('invoices.view_all')",
    '        || (',
    "          hasPerm('invoices.view')",
    '          && (',
    '            ownsOrderChildData(resource.data)',
    '            || (',
    '              resource.data.order_id is string',
    '              && ownsOrderById(resource.data.order_id)',
    '            )',
    '          )',
    '        );',
    '',
    "      allow create: if hasPerm('invoices.create')",
    "        && relationCreateBase(request.resource.data.order_id, 'invoices.view_all')",
    '        && invoiceCreateCountTransitionMatches(request.resource.data.order_id)',
    '        && relationParentMarkerMatches(',
    "          request.resource.data.order_id, 'invoices', 'create', docId,",
    "          'invoice_relation_revision'",
    '        );',
    '',
    '      allow update: if (',
    "          relationExistingChildBase(resource.data.order_id, 'invoices.view_all')",
    '          && (',
    "            changedAny(['deleted', 'active', 'deleted_at'])",
    '              ? (',
    "                hasPerm('invoices.delete')",
    '                && softDeleteOnly()',
    '                && relationParentMarkerMatches(',
    "                  resource.data.order_id, 'invoices', 'delete', docId,",
    "                  'invoice_relation_revision'",
    '                )',
    '              )',
    '              : (',
    "                hasPerm('invoices.edit')",
    "                && unchanged(['deleted', 'active', 'status', 'deleted_at'])",
    '                && relationParentMarkerMatches(',
    "                  resource.data.order_id, 'invoices', 'update', docId,",
    "                  'invoice_relation_revision'",
    '                )',
    '              )',
    '          )',
    '        )',
    '        || isAdmin();',
    '',
    '      allow delete: if isAdmin();',
    '    }',
  ),
  block(
    '    match /invoices/{docId} {',
    '      allow read: if isAdmin()',
    "        || hasPerm('invoices.view_all')",
    '        || (',
    "          hasPerm('invoices.view')",
    '          && (',
    '            ownsOrderChildData(resource.data)',
    '            || (',
    '              resource.data.order_id is string',
    '              && ownsOrderById(resource.data.order_id)',
    '            )',
    '          )',
    '        )',
    '        || (',
    "          hasAnyPerm(['orders.edit', 'orders.delete'])",
    '          && resource.data.order_id is string',
    '          && canMutateOrderById(resource.data.order_id)',
    '        );',
    '',
    '      allow create: if autoInvoiceCreateFromNewOrderAllowed(docId)',
    '        || (',
    "          hasPerm('invoices.create')",
    "          && relationCreateBase(request.resource.data.order_id, 'invoices.view_all')",
    '          && invoiceCreateCountTransitionMatches(request.resource.data.order_id)',
    '          && relationParentMarkerMatches(',
    "            request.resource.data.order_id, 'invoices', 'create', docId,",
    "            'invoice_relation_revision'",
    '          )',
    '        );',
    '',
    '      allow update: if (',
    "          changedAny(['deleted', 'active', 'deleted_at'])",
    '            ? (',
    '              (',
    "                relationExistingChildBase(resource.data.order_id, 'invoices.view_all')",
    "                && hasPerm('invoices.delete')",
    '                && softDeleteOnly()',
    '                && relationParentMarkerMatches(',
    "                  resource.data.order_id, 'invoices', 'delete', docId,",
    "                  'invoice_relation_revision'",
    '                )',
    '              )',
    '              || invoiceOrderCascadeDeleteAllowed()',
    '            )',
    '            : (',
    '              (',
    "                relationExistingChildBase(resource.data.order_id, 'invoices.view_all')",
    "                && hasPerm('invoices.edit')",
    "                && unchanged(['deleted', 'active', 'status', 'deleted_at'])",
    '                && invoiceAccountingUpdateValid(resource.data.order_id)',
    '                && relationParentMarkerMatches(',
    "                  resource.data.order_id, 'invoices', 'update', docId,",
    "                  'invoice_relation_revision'",
    '                )',
    '              )',
    '              || saleInvoiceStatusUpdateAllowed(docId)',
    '            )',
    '        )',
    '        || isAdmin();',
    '',
    '      allow delete: if isAdmin();',
    '    }',
  ),
)

await writeFile(path, source)
console.log('Guarded Firestore Rules patch applied.')
