import { readFile, writeFile } from 'node:fs/promises'

function block(...lines) {
  return lines.join('\n')
}

async function replaceOnce(path, before, after) {
  const source = await readFile(path, 'utf8')
  const count = source.split(before).length - 1
  if (count !== 1) throw new Error(`${path}: expected one guarded match, found ${count}`)
  await writeFile(path, source.replace(before, after))
}

await replaceOnce(
  'firestore.rules',
  block(
    "                request.resource.data.get('relation_last_module', '') == 'invoices'",
    '                && (',
    '                  orderInvoiceSummaryUpdateAllowed(docId)',
    '                  || orderSaleInvoiceStatusUpdateAllowed(docId)',
    '                  || orderLegacyInvoiceCreateAllowed(docId)',
    '                )',
  ),
  block(
    "                request.resource.data.get('relation_last_module', '') == 'invoices'",
    '                && (',
    "                  request.resource.data.get('relation_last_action', '') == 'create'",
    '                    ? (',
    "                      request.resource.data.get('revision', -1) == resource.data.get('revision', 0) + 1",
    '                        ? orderLegacyInvoiceCreateAllowed(docId)',
    '                        : orderInvoiceSummaryUpdateAllowed(docId)',
    '                    )',
    "                    : request.resource.data.get('relation_last_action', '') == 'update'",
    '                      ? (',
    "                        request.resource.data.get('revision', -1) == resource.data.get('revision', 0) + 1",
    '                          ? orderSaleInvoiceStatusUpdateAllowed(docId)',
    '                          : orderInvoiceSummaryUpdateAllowed(docId)',
    '                      )',
    '                      : orderInvoiceSummaryUpdateAllowed(docId)',
    '                )',
  ),
)

await replaceOnce(
  'firestore.rules',
  '    match /invoices/{docId} {',
  block(
    '    function invoiceRequestOrderExistsBefore() {',
    "      let orderId = request.resource.data.get('order_id', '');",
    '      return orderId is string',
    "        && orderId != ''",
    '        && exists(orderPath(orderId));',
    '    }',
    '',
    '    function invoiceRequestOrderRevisionAdvanced() {',
    "      let orderId = request.resource.data.get('order_id', '');",
    '      let path = orderPath(orderId);',
    '      return orderId is string',
    "        && orderId != ''",
    '        && exists(path)',
    '        && existsAfter(path)',
    "        && getAfter(path).data.get('revision', -1) == get(path).data.get('revision', 0) + 1;",
    '    }',
    '',
    '    function invoiceRequestOrderDeletedAfter() {',
    "      let orderId = request.resource.data.get('order_id', '');",
    '      let path = orderPath(orderId);',
    '      return orderId is string',
    "        && orderId != ''",
    '        && existsAfter(path)',
    "        && getAfter(path).data.get('deleted', false) == true",
    "        && getAfter(path).data.get('active', true) == false;",
    '    }',
    '',
    '    match /invoices/{docId} {',
  ),
)

await replaceOnce(
  'firestore.rules',
  block(
    '      allow create: if autoInvoiceCreateFromNewOrderAllowed(docId)',
    '        || legacyInvoiceCreateFromExistingOrderAllowed(docId)',
    '        || (',
    "          hasPerm('invoices.view_all')",
    "          && hasPerm('invoices.create')",
    "          && relationCreateBase(request.resource.data.order_id, 'invoices.view_all')",
    '          && invoiceCreateCountTransitionMatches(request.resource.data.order_id)',
    '          && relationParentMarkerMatches(',
    "            request.resource.data.order_id, 'invoices', 'create', docId,",
    "            'invoice_relation_revision'",
    '          )',
    '        );',
  ),
  block(
    '      allow create: if invoiceRequestOrderExistsBefore()',
    '        ? (',
    '          invoiceRequestOrderRevisionAdvanced()',
    '            ? legacyInvoiceCreateFromExistingOrderAllowed(docId)',
    '            : (',
    "              hasPerm('invoices.view_all')",
    "              && hasPerm('invoices.create')",
    "              && relationCreateBase(request.resource.data.order_id, 'invoices.view_all')",
    '              && invoiceCreateCountTransitionMatches(request.resource.data.order_id)',
    '              && relationParentMarkerMatches(',
    "                request.resource.data.order_id, 'invoices', 'create', docId,",
    "                'invoice_relation_revision'",
    '              )',
    '            )',
    '        )',
    '        : autoInvoiceCreateFromNewOrderAllowed(docId);',
  ),
)

await replaceOnce(
  'firestore.rules',
  block(
    '      allow update: if (',
    "          changedAny(['deleted', 'active', 'deleted_at'])",
    '            ? (',
    '              legacyInvoiceRestoreFromExistingOrderAllowed(docId)',
    '              || (',
    "                hasPerm('invoices.view_all')",
    "                && relationExistingChildBase(resource.data.order_id, 'invoices.view_all')",
    "                && hasPerm('invoices.delete')",
    '                && softDeleteOnly()',
    '                && relationParentMarkerMatches(',
    "                  resource.data.order_id, 'invoices', 'delete', docId,",
    "                  'invoice_relation_revision'",
    '                )',
    '              )',
    '              || invoiceOrderCascadeDeleteAllowed()',
    '            )',
    '            : (',
    '              (',
    "                hasPerm('invoices.view_all')",
    "                && relationExistingChildBase(resource.data.order_id, 'invoices.view_all')",
    "                && hasPerm('invoices.edit')",
    "                && unchanged(['deleted', 'active', 'status', 'deleted_at'])",
    '                && invoiceAccountingUpdateValid(resource.data.order_id)',
    '                && relationParentMarkerMatches(',
    "                  resource.data.order_id, 'invoices', 'update', docId,",
    "                  'invoice_relation_revision'",
    '                )',
    '              )',
    '              || saleInvoiceStatusUpdateAllowed(docId)',
    '            )',
    '        )',
    '        || isAdmin();',
  ),
  block(
    '      allow update: if (',
    "          changedAny(['deleted', 'active', 'deleted_at'])",
    '            ? (',
    "              request.resource.data.get('active', false) == true",
    "                && request.resource.data.get('deleted', true) == false",
    '                ? legacyInvoiceRestoreFromExistingOrderAllowed(docId)',
    '                : (',
    '                  invoiceRequestOrderDeletedAfter()',
    '                    ? invoiceOrderCascadeDeleteAllowed()',
    '                    : (',
    "                      hasPerm('invoices.view_all')",
    "                      && relationExistingChildBase(resource.data.order_id, 'invoices.view_all')",
    "                      && hasPerm('invoices.delete')",
    '                      && softDeleteOnly()',
    '                      && relationParentMarkerMatches(',
    "                        resource.data.order_id, 'invoices', 'delete', docId,",
    "                        'invoice_relation_revision'",
    '                      )',
    '                    )',
    '                )',
    '            )',
    '            : (',
    '              invoiceRequestOrderRevisionAdvanced()',
    '                ? saleInvoiceStatusUpdateAllowed(docId)',
    '                : (',
    "                  hasPerm('invoices.view_all')",
    "                  && relationExistingChildBase(resource.data.order_id, 'invoices.view_all')",
    "                  && hasPerm('invoices.edit')",
    "                  && unchanged(['deleted', 'active', 'status', 'deleted_at'])",
    '                  && invoiceAccountingUpdateValid(resource.data.order_id)',
    '                  && relationParentMarkerMatches(',
    "                    resource.data.order_id, 'invoices', 'update', docId,",
    "                    'invoice_relation_revision'",
    '                  )',
    '                )',
    '            )',
    '        )',
    '        || isAdmin();',
  ),
)

console.log('Invoice Rules dispatch optimized.')
