import { readFile, writeFile } from 'node:fs/promises'

const block = (...lines) => lines.join('\n')

async function replaceOnce(path, before, after) {
  const source = await readFile(path, 'utf8')
  const count = source.split(before).length - 1
  if (count !== 1) throw new Error(`${path}: expected exactly one guarded match, found ${count}`)
  await writeFile(path, source.replace(before, after))
}

await replaceOnce(
  'utils/orderInvoiceFlow.mjs',
  block(
    'export function validateAccountingInvoice(input = {}) {',
    '  const status = normalizeInvoiceStatus(input.invoice_status)',
    '  if (!ACCOUNTING_INVOICE_STATUSES.includes(status)) {',
    "    return 'Trạng thái hóa đơn không hợp lệ.'",
    '  }',
    '  const amount = Number(input.invoice_amount)',
    '  if (!Number.isFinite(amount) || amount < 0) {',
    "    return 'Giá trị hóa đơn không được âm.'",
    '  }',
    "  if (status === 'Đã xuất') {",
    "    if (!text(input.invoice_number)) return 'Vui lòng nhập số hóa đơn trước khi chuyển sang Đã xuất.'",
    "    if (!text(input.invoice_date)) return 'Vui lòng nhập ngày hóa đơn trước khi chuyển sang Đã xuất.'",
    '  }',
    "  return ''",
    '}',
  ),
  block(
    'export function validateAccountingInvoice(input = {}) {',
    '  const status = normalizeInvoiceStatus(input.invoice_status)',
    '  if (!ACCOUNTING_INVOICE_STATUSES.includes(status)) {',
    "    return 'Trạng thái hóa đơn không hợp lệ.'",
    '  }',
    "  return ''",
    '}',
  ),
)

await replaceOnce(
  'composables/useAtomicOrderSave.ts',
  "  mode: 'create' | 'status_update'",
  "  mode: 'create' | 'legacy_create' | 'status_update'",
)

await replaceOnce(
  'composables/useAtomicOrderSave.ts',
  block(
    "    } else if (invoiceMutation?.mode === 'create') {",
    "      throw new Error('Không được tạo thêm hóa đơn khi sửa đơn hàng.')",
    '    }',
  ),
  block(
    "    } else if (invoiceMutation?.mode === 'create') {",
    "      throw new Error('Không được tạo thêm hóa đơn khi sửa đơn hàng.')",
    "    } else if (invoiceMutation?.mode === 'legacy_create'",
    '      && invoiceMutation.invoiceId !== buildOrderInvoiceId(input.orderId)) {',
    "      throw new Error('ID hóa đơn legacy không khớp đơn hàng.')",
    '    }',
  ),
)

await replaceOnce(
  'composables/useAtomicOrderSave.ts',
  "      updateInvoiceStatus: invoiceMutation?.mode === 'status_update',",
  "      updateInvoiceStatus: invoiceMutation?.mode === 'status_update' || invoiceMutation?.mode === 'legacy_create',",
)

await replaceOnce(
  'composables/useAtomicOrderSave.ts',
  block(
    "      let requestedInvoiceStatus = ''",
    '      let existingInvoice: Record<string, any> | null = null',
    '      if (invoiceMutation) {',
    '        requestedInvoiceStatus = assertSaleInvoiceStatus(invoiceMutation.requestedStatus)',
    "        if (invoiceMutation.mode === 'status_update') {",
    '          if (!invoiceSnapshot?.exists()) {',
    "            throw new Error('Không tìm thấy hóa đơn đang hoạt động của đơn. Hãy tải lại dữ liệu.')",
    '          }',
    '          existingInvoice = invoiceSnapshot.data()',
    '          if (existingInvoice.order_id !== input.orderId) {',
    "            throw new Error('Hóa đơn không thuộc đơn hàng đang sửa.')",
    '          }',
    '          const currentInvoiceStatus = normalizeInvoiceStatus(existingInvoice.invoice_status)',
    '          const expectedStatus = normalizeInvoiceStatus(invoiceMutation.expectedStatus)',
    '          if (currentInvoiceStatus !== expectedStatus) {',
    "            throw new Error('Trạng thái hóa đơn đã được cập nhật ở phiên khác. Hãy tải lại dữ liệu.')",
    '          }',
    '          if (toNumber(existingInvoice.relation_revision) !== toNumber(invoiceMutation.expectedRelationRevision)) {',
    "            throw new Error('Phiên bản hóa đơn đã thay đổi. Hãy tải lại dữ liệu trước khi lưu.')",
    '          }',
    '          if (normalizeInvoiceStatus(existingOrder.invoice_status) !== currentInvoiceStatus) {',
    "            throw new Error('Trạng thái hóa đơn và đơn hàng đang lệch nhau. Vui lòng tải lại dữ liệu.')",
    '          }',
    '          if (toNumber(existingOrder.invoice_record_count) !== 1) {',
    "            throw new Error('Đơn hàng phải có đúng một hóa đơn hoạt động để Sale cập nhật trạng thái.')",
    '          }',
    '          if (!canSaleTransitionInvoiceStatus(currentInvoiceStatus, requestedInvoiceStatus)) {',
    "            throw new Error('Hóa đơn đã xuất hoặc trạng thái chuyển đổi không hợp lệ.')",
    '          }',
    '        }',
    '      }',
  ),
  block(
    "      let requestedInvoiceStatus = ''",
    '      let existingInvoice: Record<string, any> | null = null',
    '      if (invoiceMutation) {',
    '        const persistedOrderInvoiceStatus = normalizeInvoiceStatus(existingOrder.invoice_status)',
    "        if (invoiceMutation.mode === 'legacy_create' && persistedOrderInvoiceStatus === 'Đã xuất') {",
    '          requestedInvoiceStatus = normalizeInvoiceStatus(invoiceMutation.requestedStatus)',
    "          if (requestedInvoiceStatus !== 'Đã xuất') {",
    "            throw new Error('Đơn legacy đã xuất phải giữ nguyên trạng thái Đã xuất khi tạo hóa đơn.')",
    '          }',
    '        } else {',
    '          requestedInvoiceStatus = assertSaleInvoiceStatus(invoiceMutation.requestedStatus)',
    '        }',
    "        if (invoiceMutation.mode === 'legacy_create') {",
    '          if (invoiceSnapshot?.exists()) {',
    "            throw new Error('Đơn hàng đã có document hóa đơn theo ID tự động. Hãy tải lại dữ liệu.')",
    '          }',
    '          if (toNumber(existingOrder.invoice_record_count) > 0) {',
    "            throw new Error('Đơn hàng đang ghi nhận đã có hóa đơn. Hãy chạy đồng bộ quan hệ trước khi lưu.')",
    '          }',
    "        } else if (invoiceMutation.mode === 'status_update') {",
    '          if (!invoiceSnapshot?.exists()) {',
    "            throw new Error('Không tìm thấy hóa đơn đang hoạt động của đơn. Hãy tải lại dữ liệu.')",
    '          }',
    '          existingInvoice = invoiceSnapshot.data()',
    '          if (existingInvoice.order_id !== input.orderId) {',
    "            throw new Error('Hóa đơn không thuộc đơn hàng đang sửa.')",
    '          }',
    '          const currentInvoiceStatus = normalizeInvoiceStatus(existingInvoice.invoice_status)',
    '          const expectedStatus = normalizeInvoiceStatus(invoiceMutation.expectedStatus)',
    '          if (currentInvoiceStatus !== expectedStatus) {',
    "            throw new Error('Trạng thái hóa đơn đã được cập nhật ở phiên khác. Hãy tải lại dữ liệu.')",
    '          }',
    '          if (toNumber(existingInvoice.relation_revision) !== toNumber(invoiceMutation.expectedRelationRevision)) {',
    "            throw new Error('Phiên bản hóa đơn đã thay đổi. Hãy tải lại dữ liệu trước khi lưu.')",
    '          }',
    '          if (normalizeInvoiceStatus(existingOrder.invoice_status) !== currentInvoiceStatus) {',
    "            throw new Error('Trạng thái hóa đơn và đơn hàng đang lệch nhau. Vui lòng tải lại dữ liệu.')",
    '          }',
    '          if (toNumber(existingOrder.invoice_record_count) !== 1) {',
    "            throw new Error('Đơn hàng phải có đúng một hóa đơn hoạt động để Sale cập nhật trạng thái.')",
    '          }',
    '          if (!canSaleTransitionInvoiceStatus(currentInvoiceStatus, requestedInvoiceStatus)) {',
    "            throw new Error('Hóa đơn đã xuất hoặc trạng thái chuyển đổi không hợp lệ.')",
    '          }',
    '        }',
    '      }',
  ),
)

await replaceOnce(
  'composables/useAtomicOrderSave.ts',
  block(
    "      const invoiceRelationPatch = invoiceMutation?.mode === 'create'",
    '        ? {',
    '            invoice_status: requestedInvoiceStatus,',
    '            invoice_record_count: 1,',
    '            invoice_relation_revision: 1,',
    '            relation_lock_version: 1,',
    "            relation_last_module: 'invoices',",
    "            relation_last_action: 'create',",
    '            relation_last_document_id: invoiceMutation.invoiceId,',
    '            relation_updated_by: actor,',
    '            relation_updated_at: serverTimestamp(),',
    '          }',
    "        : invoiceMutation?.mode === 'status_update'",
    '          ? {',
    '              invoice_status: requestedInvoiceStatus,',
    '              invoice_record_count: toNumber(existingOrder.invoice_record_count),',
    '              invoice_relation_revision: toNumber(existingOrder.invoice_relation_revision) + 1,',
    '              relation_lock_version: 1,',
    "              relation_last_module: 'invoices',",
    "              relation_last_action: 'update',",
    '              relation_last_document_id: invoiceMutation.invoiceId,',
    '              relation_updated_by: actor,',
    '              relation_updated_at: serverTimestamp(),',
    '            }',
    '          : {}',
  ),
  block(
    "      const invoiceRelationPatch = invoiceMutation?.mode === 'create'",
    '        ? {',
    '            invoice_status: requestedInvoiceStatus,',
    '            invoice_record_count: 1,',
    '            invoice_relation_revision: 1,',
    '            relation_lock_version: 1,',
    "            relation_last_module: 'invoices',",
    "            relation_last_action: 'create',",
    '            relation_last_document_id: invoiceMutation.invoiceId,',
    '            relation_updated_by: actor,',
    '            relation_updated_at: serverTimestamp(),',
    '          }',
    "        : invoiceMutation?.mode === 'legacy_create'",
    '          ? {',
    '              invoice_status: requestedInvoiceStatus,',
    '              invoice_record_count: 1,',
    '              invoice_relation_revision: Math.max(1, toNumber(existingOrder.invoice_relation_revision) + 1),',
    '              relation_lock_version: 1,',
    "              relation_last_module: 'invoices',",
    "              relation_last_action: 'create',",
    '              relation_last_document_id: invoiceMutation.invoiceId,',
    '              relation_updated_by: actor,',
    '              relation_updated_at: serverTimestamp(),',
    '            }',
    "          : invoiceMutation?.mode === 'status_update'",
    '            ? {',
    '                invoice_status: requestedInvoiceStatus,',
    '                invoice_record_count: toNumber(existingOrder.invoice_record_count),',
    '                invoice_relation_revision: toNumber(existingOrder.invoice_relation_revision) + 1,',
    '                relation_lock_version: 1,',
    "                relation_last_module: 'invoices',",
    "                relation_last_action: 'update',",
    '                relation_last_document_id: invoiceMutation.invoiceId,',
    '                relation_updated_by: actor,',
    '                relation_updated_at: serverTimestamp(),',
    '              }',
    '            : {}',
  ),
)

await replaceOnce(
  'composables/useAtomicOrderSave.ts',
  "      if (invoiceMutation?.mode === 'create' && invoiceRef) {",
  "      if ((invoiceMutation?.mode === 'create' || invoiceMutation?.mode === 'legacy_create') && invoiceRef) {",
)

await replaceOnce(
  'composables/useAtomicOrderSave.ts',
  block(
    '          relation_revision: 1,',
    '          last_operation_id: operationId,',
  ),
  block(
    '          relation_revision: toNumber(invoiceRelationPatch.invoice_relation_revision),',
    '          last_operation_id: operationId,',
  ),
)

await replaceOnce(
  'pages/orders.vue',
  block(
    '    let invoiceMutation: any',
    '    if (!editing.value) {',
    '      invoiceMutation = {',
    "        mode: 'create',",
    '        invoiceId: buildOrderInvoiceId(form.id),',
    '        requestedStatus: requestedInvoiceStatus,',
    '        payload: {',
    "          tax_code: selectedCustomer?.tax_code || '',",
    "          company_name: selectedCustomer?.company_name || '',",
    "          billing_address: selectedCustomer?.billing_address || '',",
    "          note: '',",
    '        },',
    '      }',
    "    } else if (persistedInvoiceStatus !== 'Đã xuất' && invoiceStatusChangeRequested(persistedInvoiceStatus, requestedInvoiceStatus)) {",
    '      const activeInvoices = (await loadScopedInvoicesForOrders([editing.value], true)).filter(isActiveOrderRelation) as InvoiceDoc[]',
    '      const currentInvoice = selectCanonicalInvoice(activeInvoices) as InvoiceDoc | null',
    "      if (!currentInvoice) throw new Error('Không tìm thấy hóa đơn đang hoạt động của đơn. Hãy tải lại dữ liệu.')",
    '      invoiceMutation = {',
    "        mode: 'status_update',",
    '        invoiceId: currentInvoice.id,',
    '        requestedStatus: requestedInvoiceStatus,',
    '        expectedStatus: currentInvoice.invoice_status,',
    '        expectedRelationRevision: toNumber(currentInvoice.relation_revision),',
    '      }',
    '    }',
  ),
  block(
    '    let invoiceMutation: any',
    '    if (!editing.value) {',
    '      invoiceMutation = {',
    "        mode: 'create',",
    '        invoiceId: buildOrderInvoiceId(form.id),',
    '        requestedStatus: requestedInvoiceStatus,',
    '        payload: {',
    "          tax_code: selectedCustomer?.tax_code || '',",
    "          company_name: selectedCustomer?.company_name || '',",
    "          billing_address: selectedCustomer?.billing_address || '',",
    "          note: '',",
    '        },',
    '      }',
    '    } else {',
    '      const persistedInvoiceCount = toNumber(editing.value.invoice_record_count)',
    "      const statusChanged = persistedInvoiceStatus !== 'Đã xuất'",
    '        && invoiceStatusChangeRequested(persistedInvoiceStatus, requestedInvoiceStatus)',
    '      if (persistedInvoiceCount !== 1 || statusChanged) {',
    '        const activeInvoices = (await loadScopedInvoicesForOrders([editing.value], true))',
    '          .filter(isActiveOrderRelation) as InvoiceDoc[]',
    '        if (activeInvoices.length > 1) {',
    "          throw new Error('Đơn hàng có nhiều hóa đơn đang hoạt động. Hãy xử lý trùng trước khi lưu.')",
    '        }',
    '        const currentInvoice = selectCanonicalInvoice(activeInvoices) as InvoiceDoc | null',
    '        if (!currentInvoice) {',
    '          invoiceMutation = {',
    "            mode: 'legacy_create',",
    '            invoiceId: buildOrderInvoiceId(form.id),',
    '            requestedStatus: requestedInvoiceStatus,',
    '            payload: {',
    "              tax_code: selectedCustomer?.tax_code || '',",
    "              company_name: selectedCustomer?.company_name || '',",
    "              billing_address: selectedCustomer?.billing_address || '',",
    "              note: '',",
    '            },',
    '          }',
    '        } else if (statusChanged) {',
    '          invoiceMutation = {',
    "            mode: 'status_update',",
    '            invoiceId: currentInvoice.id,',
    '            requestedStatus: requestedInvoiceStatus,',
    '            expectedStatus: currentInvoice.invoice_status,',
    '            expectedRelationRevision: toNumber(currentInvoice.relation_revision),',
    '          }',
    '        } else if (persistedInvoiceCount !== 1) {',
    "          throw new Error('Đơn hàng đã có hóa đơn nhưng dữ liệu liên kết chưa đồng bộ. Hãy chạy đồng bộ hóa đơn legacy trước.')",
    '        }',
    '      }',
    '    }',
  ),
)

await replaceOnce(
  'firestore.rules',
  block(
    '    function invoiceAccountingUpdateValid(orderId) {',
    '  let path = orderPath(orderId);',
    '  return (',
    "      unchanged(['invoice_status'])",
    "      || accountingInvoiceStatusValue(request.resource.data.get('invoice_status', ''))",
    '    )',
    '    && invoiceAmountValid(request.resource.data)',
    '    && issuedInvoiceFieldsValid(request.resource.data)',
    "    && request.resource.data.get('id', '') == resource.data.get('id', '')",
    '    && (',
    "      unchanged(['relation_revision'])",
    "      || request.resource.data.get('relation_revision', -1) == resource.data.get('relation_revision', 0) + 1",
    '    )',
    '    && existsAfter(path)',
    "    && getAfter(path).data.get('invoice_status', '') == request.resource.data.get('invoice_status', '');",
    '}',
  ),
  block(
    '    function invoiceAccountingUpdateValid(orderId) {',
    '  let path = orderPath(orderId);',
    '  return (',
    "      unchanged(['invoice_status'])",
    "      || accountingInvoiceStatusValue(request.resource.data.get('invoice_status', ''))",
    '    )',
    "    && request.resource.data.get('id', '') == resource.data.get('id', '')",
    '    && (',
    "      unchanged(['relation_revision'])",
    "      || request.resource.data.get('relation_revision', -1) == resource.data.get('relation_revision', 0) + 1",
    '    )',
    '    && existsAfter(path)',
    "    && getAfter(path).data.get('invoice_status', '') == request.resource.data.get('invoice_status', '');",
    '}',
  ),
)

await replaceOnce(
  'firestore.rules',
  block(
    '    }',
    '',
    '    function invoiceAccountingUpdateValid(orderId) {',
  ),
  block(
    '    }',
    '',
    '    function legacyInvoiceCreateFromExistingOrderAllowed(invoiceId) {',
    "      let orderId = request.resource.data.get('order_id', '');",
    '      let path = orderPath(orderId);',
    '      let before = get(path).data;',
    '      let after = getAfter(path).data;',
    "      return hasPerm('orders.edit')",
    '        && orderId is string',
    "        && orderId != ''",
    '        && exists(path)',
    '        && existsAfter(path)',
    '        && orderDataIsActive(before)',
    '        && orderDataIsActive(after)',
    "        && (ownsOrderData(before) || hasPerm('orders.view_all') || isAdmin())",
    "        && invoiceId == 'inv_' + orderId",
    "        && request.resource.data.get('id', '') == invoiceId",
    "        && request.resource.data.get('order_code', '') == before.get('order_code', '')",
    '        && requestMatchesOrderData(before)',
    "        && request.resource.data.get('created_by', '').lower() == email()",
    "        && request.resource.data.get('invoice_number', '') == ''",
    "        && request.resource.data.get('invoice_date', '') == ''",
    "        && request.resource.data.get('invoice_status', '') == after.get('invoice_status', '')",
    '        && (',
    "          before.get('invoice_status', '') == 'Đã xuất'",
    "            ? request.resource.data.get('invoice_status', '') == 'Đã xuất'",
    "            : saleInvoiceStatusValue(request.resource.data.get('invoice_status', ''))",
    '        )',
    '        && invoiceAmountValid(request.resource.data)',
    "        && request.resource.data.get('invoice_amount', -1) == after.get('payable_amount', -2)",
    "        && request.resource.data.get('relation_revision', -1) == after.get('invoice_relation_revision', -2)",
    "        && request.resource.data.get('last_operation_id', '') == after.get('last_operation_id', '')",
    "        && request.resource.data.get('status', '') == 'active'",
    "        && request.resource.data.get('active', false) == true",
    "        && request.resource.data.get('deleted', true) == false",
    "        && request.resource.data.get('created_at', null) == request.time",
    "        && request.resource.data.get('updated_at', null) == request.time",
    "        && after.get('invoice_record_count', -1) == 1",
    "        && after.get('relation_lock_version', 0) == 1",
    "        && relationMetadataMatches(after, 'invoices', 'create', invoiceId)",
    "        && after.get('relation_updated_at', null) == request.time;",
    '    }',
    '',
    '    function invoiceAccountingUpdateValid(orderId) {',
  ),
)

await replaceOnce(
  'firestore.rules',
  block(
    "        && getAfter(childPath).data.get('invoice_status', '') == request.resource.data.get('invoice_status', '');",
    '    }',
    '',
    '    function invoiceOrderCascadeDeleteAllowed() {',
  ),
  block(
    "        && getAfter(childPath).data.get('invoice_status', '') == request.resource.data.get('invoice_status', '');",
    '    }',
    '',
    '    function orderLegacyInvoiceCreateKeepsOtherSystemFields() {',
    '      return unchanged([',
    "          'paid_amount', 'debt_amount', 'computed_payment_status', 'payment_status',",
    "          'payment_count', 'deposit_count', 'collect_count',",
    "          'warehouse_fulfillment_status', 'warehouse_request_status',",
    "          'printing_progress_count', 'printing_lock_version', 'printing_last_action',",
    "          'printing_last_print_order_id', 'printing_lock_updated_by', 'printing_lock_updated_at',",
    "          'payment_record_count', 'shipment_record_count',",
    "          'payment_relation_revision', 'shipment_relation_revision',",
    "          'shipment_status', 'shipping_fee_total', 'cod_amount_total',",
    "          'deleted', 'active', 'status', 'deleted_at'",
    '        ]);',
    '    }',
    '',
    '    function orderLegacyInvoiceCreateAllowed(orderId) {',
    "      let invoiceId = request.resource.data.get('relation_last_document_id', '');",
    '      let childPath = invoicePath(invoiceId);',
    "      let currentRevision = resource.data.get('invoice_relation_revision', 0);",
    "      return hasPerm('orders.edit')",
    "        && (ownsOrderData(resource.data) || hasPerm('orders.view_all') || isAdmin())",
    '        && orderIdentityUnchanged()',
    '        && orderLegacyInvoiceCreateKeepsOtherSystemFields()',
    "        && fulfillmentStatus() != 'da_xuat_du'",
    "        && resource.data.get('invoice_record_count', 0) == 0",
    "        && request.resource.data.get('invoice_record_count', -1) == 1",
    "        && request.resource.data.get('invoice_relation_revision', -1) == currentRevision + 1",
    "        && request.resource.data.get('relation_lock_version', 0) == 1",
    '        && (',
    "          resource.data.get('invoice_status', '') == 'Đã xuất'",
    "            ? request.resource.data.get('invoice_status', '') == 'Đã xuất'",
    "            : saleInvoiceStatusValue(request.resource.data.get('invoice_status', ''))",
    '        )',
    "        && request.resource.data.get('revision', -1) == resource.data.get('revision', 0) + 1",
    "        && validBoundedString(request.resource.data.get('last_operation_id', ''), 1, 200)",
    "        && invoiceId == 'inv_' + orderId",
    "        && relationMetadataMatches(request.resource.data, 'invoices', 'create', invoiceId)",
    "        && request.resource.data.get('relation_updated_at', null) == request.time",
    "        && request.resource.data.get('updated_at', null) == request.time",
    '        && !exists(childPath)',
    '        && existsAfter(childPath)',
    '        && activeRelationData(getAfter(childPath).data)',
    "        && getAfter(childPath).data.get('order_id', '') == orderId",
    "        && getAfter(childPath).data.get('invoice_status', '') == request.resource.data.get('invoice_status', '')",
    "        && getAfter(childPath).data.get('relation_revision', -1) == request.resource.data.get('invoice_relation_revision', -2)",
    "        && getAfter(childPath).data.get('last_operation_id', '') == request.resource.data.get('last_operation_id', '');",
    '    }',
    '',
    '    function invoiceOrderCascadeDeleteAllowed() {',
  ),
)

await replaceOnce(
  'firestore.rules',
  block(
    '                  orderInvoiceSummaryUpdateAllowed(docId)',
    '                  || orderSaleInvoiceStatusUpdateAllowed(docId)',
  ),
  block(
    '                  orderInvoiceSummaryUpdateAllowed(docId)',
    '                  || orderSaleInvoiceStatusUpdateAllowed(docId)',
    '                  || orderLegacyInvoiceCreateAllowed(docId)',
  ),
)

await replaceOnce(
  'firestore.rules',
  block(
    '      allow create: if autoInvoiceCreateFromNewOrderAllowed(docId)',
    '        || (',
  ),
  block(
    '      allow create: if autoInvoiceCreateFromNewOrderAllowed(docId)',
    '        || legacyInvoiceCreateFromExistingOrderAllowed(docId)',
    '        || (',
  ),
)

await replaceOnce(
  'tests/order-invoice-flow.client.test.mjs',
  block(
    "test('validation kế toán bắt buộc dữ liệu khi chuyển Đã xuất', () => {",
    "  assert.equal(validateAccountingInvoice({ invoice_status: 'Không xuất', invoice_amount: 0 }), '')",
    "  assert.equal(validateAccountingInvoice({ invoice_status: 'Yêu cầu xuất', invoice_amount: 100 }), '')",
    "  assert.match(validateAccountingInvoice({ invoice_status: 'Đã xuất', invoice_amount: 100 }), /số hóa đơn/)",
    "  assert.match(validateAccountingInvoice({ invoice_status: 'Đã xuất', invoice_amount: 100, invoice_number: 'HD-01' }), /ngày hóa đơn/)",
    '  assert.equal(validateAccountingInvoice({',
    "    invoice_status: 'Đã xuất', invoice_amount: 100, invoice_number: 'HD-01', invoice_date: '2026-07-27',",
    "  }), '')",
    "  assert.match(validateAccountingInvoice({ invoice_status: 'Yêu cầu xuất', invoice_amount: -1 }), /không được âm/)",
    '})',
  ),
  block(
    "test('validation kế toán chỉ kiểm tra trạng thái hợp lệ', () => {",
    "  assert.equal(validateAccountingInvoice({ invoice_status: 'Không xuất' }), '')",
    "  assert.equal(validateAccountingInvoice({ invoice_status: 'Yêu cầu xuất', invoice_amount: -1 }), '')",
    "  assert.equal(validateAccountingInvoice({ invoice_status: 'Đã xuất', invoice_number: '', invoice_date: '' }), '')",
    "  assert.match(validateAccountingInvoice({ invoice_status: 'Sai trạng thái' }), /không hợp lệ/)",
    '})',
  ),
)

await replaceOnce(
  'tests/order-invoice-flow.rules.test.mjs',
  block(
    "test('kế toán thiếu invoices.edit hoặc thiếu dữ liệu bắt buộc không được chuyển Đã xuất', async () => {",
    '  const viewerDb = env.authenticatedContext(NO_EDIT, { email: NO_EDIT }).firestore()',
    '  await assertFails(accountantStatusBatch(viewerDb, { actor: NO_EDIT }).commit())',
    '',
    '  const accountantDb = env.authenticatedContext(ACCOUNTANT, { email: ACCOUNTANT }).firestore()',
    "  await assertFails(accountantStatusBatch(accountantDb, { invoiceNumber: '' }).commit())",
    "  await assertFails(accountantStatusBatch(accountantDb, { invoiceDate: '' }).commit())",
    '  await assertFails(accountantStatusBatch(accountantDb, { amount: -1 }).commit())',
    '})',
  ),
  block(
    "test('kế toán thiếu invoices.edit bị chặn nhưng dữ liệu số tiền, số và ngày không còn bắt buộc', async () => {",
    '  const viewerDb = env.authenticatedContext(NO_EDIT, { email: NO_EDIT }).firestore()',
    '  await assertFails(accountantStatusBatch(viewerDb, { actor: NO_EDIT }).commit())',
    '',
    '  const accountantDb = env.authenticatedContext(ACCOUNTANT, { email: ACCOUNTANT }).firestore()',
    "  await assertSucceeds(accountantStatusBatch(accountantDb, { invoiceNumber: '', invoiceDate: '', amount: -1 }).commit())",
    '})',
  ),
)

await replaceOnce(
  'tests/order-invoice-legacy-backfill.rules.test.mjs',
  block(
    '  ]) {',
    '    await env.clearFirestore()',
    "    await beforeEach[Symbol.for('noop')]",
    '    await env.withSecurityRulesDisabled(async context => {',
    '      const db = context.firestore()',
    '      await Promise.all([',
    "        setDoc(doc(db, 'users', SALE), { email: SALE, active: true, deleted: false, permissions_flat: ['orders.view', 'orders.edit'] }),",
    "        setDoc(doc(db, 'orders', 'order-legacy'), baseOrder('order-legacy')),",
    '      ])',
    '    })',
    '    const db = env.authenticatedContext(SALE, { email: SALE }).firestore()',
    '    await assertFails(legacyCreateBatch(db, invalid).commit())',
    '  }',
  ),
  block(
    '  ]) {',
    '    const db = env.authenticatedContext(SALE, { email: SALE }).firestore()',
    '    await assertFails(legacyCreateBatch(db, invalid).commit())',
    '  }',
  ),
)

await replaceOnce(
  'tests/order-invoice-legacy-backfill.client.test.mjs',
  "  assert.doesNotMatch(invoicesPage, /invoice_amount: toNumber\\(form\\.invoice_amount\\)/)\n",
  '',
)

const packagePath = 'package.json'
const pkg = JSON.parse(await readFile(packagePath, 'utf8'))
pkg.scripts['migrate:backfill-order-invoices'] = 'node scripts/backfill-order-invoices.mjs'
for (const testFile of [
  'tests/order-invoice-legacy-backfill.client.test.mjs',
  'tests/order-invoice-legacy-backfill.rules.test.mjs',
]) {
  if (!pkg.scripts['test:rules'].includes(testFile)) {
    pkg.scripts['test:rules'] = pkg.scripts['test:rules'].replace(
      'tests/order-item-dependencies.client.test.mjs',
      `${testFile} tests/order-item-dependencies.client.test.mjs`,
    )
  }
}
await writeFile(packagePath, `${JSON.stringify(pkg, null, 2)}\n`)

console.log('Guarded legacy invoice patch applied.')
