export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useAtomicOrderRelations } from '../composables/useAtomicOrderRelations';
export { useAtomicOrderSave, AtomicOrderSaveInput, AtomicOrderSaveResult } from '../composables/useAtomicOrderSave';
export { useAuth } from '../composables/useAuth';
export { useConfirmDialog } from '../composables/useConfirmDialog';
export { useCustomerManagement } from '../composables/useCustomerManagement';
export { DASHBOARD_CACHE_NAMESPACE, DASHBOARD_CACHE_TAGS, invalidateDashboardSnapshotCache, useDashboardSnapshot } from '../composables/useDashboardSnapshot';
export { useFirebaseServices } from '../composables/useFirebaseServices';
export { useFulfilledOrderMetadataSave } from '../composables/useFulfilledOrderMetadataSave';
export { WAREHOUSE_NOTIFICATION_PERMISSIONS, WAREHOUSE_NOTIFICATION_TYPES, resolveSaleNotificationRecipients, buildNotificationPayload, useNotifications, NotificationPayloadInput, SaleNotificationRecipientInput } from '../composables/useNotifications';
export { useOrderLogic } from '../composables/useOrderLogic';
export { useOrderPriceSave } from '../composables/useOrderPriceSave';
export { useOrderPrintingDeleteGuard } from '../composables/useOrderPrintingDeleteGuard';
export { usePrintingProgress, PrintItemInput } from '../composables/usePrintingProgress';
export { usePrintingScopedQueries } from '../composables/usePrintingScopedQueries';
export { cachedQuery, invalidateQueryCacheTags, clearSharedQueryCache, removeSharedQueryCacheKey } from '../composables/useQueryCache';
export { resetReferenceDataCacheSync, useReferenceDataCache } from '../composables/useReferenceDataCache';
export { useRepo } from '../composables/useRepo';
export { EXPORT_REQUEST_OWNER_FIELDS, invalidateScopedCache, CursorPage } from '../composables/useScopedQueries';
export { invalidateScopedQueriesClientCache, useScopedQueriesClient } from '../composables/useScopedQueriesClient';
export { useUi } from '../composables/useUi';
export { useVietnamProvinces, VietnamDistrict } from '../composables/useVietnamProvinces';
export { useWarehouseCostTransactions } from '../composables/useWarehouseCostTransactions';
export { useWarehouseLogic, FulfillmentRow } from '../composables/useWarehouseLogic';
export { useWarehouseTransactionsClient } from '../composables/useWarehouseTransactionsClient';
export { normalizePermissionList, effectivePermissionsFromUser, isAdminFromPermissions, isActiveAuthorizationUser, authorizationFingerprint, authorizationCacheToken, authorizationChanged } from '../utils/authorizationState';
export { applyCommercialPrintAlignment } from '../utils/commercialPrintAlignment';
export { appendUniqueRows, createCursorState } from '../utils/cursorPagination';
export { generateCustomerCode, isValidCustomerCode } from '../utils/customerCode';
export { DASHBOARD_RECENT_LIMIT, DASHBOARD_ALERT_LIMIT, DASHBOARD_SOURCE_COLLECTIONS, DASHBOARD_PERIODS, DASHBOARD_ORDER_CLASSIFICATIONS, dashboardTimestampValue, buildDashboardSnapshot } from '../utils/dashboardSnapshot';
export { EXPORT_REQUEST_STATUSES, canonicalExportRequestStatus, activeExportOrderId, exportReleaseSequence, nextExportReleaseSequence, requestExportOrderId, requestExternalExportOrderId, canAcceptExportRequest, canRejectExportRequest, buildAcceptedRequestPatch, buildRejectedRequestPatch, canReleaseExportRequest, canCancelExportRequestRelease, externalExportOrderId, canCancelExternalExportRequestRelease, externalExportLifecycleLinkError, exportLifecycleLinkError, appendExportLifecycleTimeline, buildReleasedRequestPatch, buildCancelledReleaseRequestPatch, isExternalExportRequestRelease, canReleaseExportRequestExternally, buildExternalReleasedRequestPatch, buildCancelledExternalReleaseRequestPatch, buildGeneratedExportLifecycleFields } from '../utils/exportLifecycle';
export { fallbackOrderPatch, WarehouseOrderSummaryPatch } from '../utils/fallbackOrderPatch';
export { firebaseErrorMessage, reportFirebaseError, reportPermissionError, FirebaseErrorContext } from '../utils/firebaseErrors';
export { normalizeText, normalizeEmail, toNumber, round2, money, nowDateTimeLocal, dateTimeLocal, formatDateTime, makeId, makeCode, isActive, safeJsonParse, BUSINESS_TIME_ZONE, businessDateKey, monthKey, todayKey } from '../utils/format';
export { matchesKeyword, uniqueOptions, isDateInRange, toDateKey, DateLike } from '../utils/listFilters';
export { LOGO_FILTER_VALUES, LOGO_FILTER_OPTIONS, hasMeaningfulLogo, rowsHaveLogo, matchesLogoPresenceFilter } from '../utils/logoFilter';
export { NOTIFICATION_SOURCE_LIMIT, NOTIFICATION_READ_STATE_LIMIT, NOTIFICATION_VISIBLE_LIMIT, notificationTimestamp, buildNotificationWindow } from '../utils/notificationWindow';
export { FIRESTORE_WRITE_LIMIT, ORDER_EDIT_SYSTEM_FIELDS, ORDER_IMMUTABLE_IDENTITY_FIELDS, stripOrderEditSystemFields, preservePersistedOrderIdentityForEdit, assertOrderEditIdentityUnchanged, buildOrderPaymentSummaryForPayable, resolveOrderOwnershipForSave, numericRevision, uniqueDocumentIds, comparableOrderItem, orderItemContentChanged, planAtomicOrderItems, buildOrderItemLifecyclePatch, shouldReadExistingInvoiceSnapshot, estimateAtomicOrderWrites, assertAtomicOrderWriteLimit, nextOrderRevision, assertExpectedOrderRevision, buildOrderOperationId } from '../utils/orderAtomicSave';
export { ORDER_SEQUENCE_START, normalizeUserCode, userCodeValidationError, normalizeCustomerCode, customerCodeValidationError, buildOrderCode } from '../utils/orderCode';
export { FULFILLED_ORDER_STATUS, FULFILLED_ORDER_METADATA_FIELDS, FULFILLED_ORDER_METADATA_WRITE_FIELDS, isFulfilledOrder, normalizeFulfilledOrderMetadata, validateFulfilledInvoiceStatusTransition, fulfilledOrderMetadataChanged, buildFulfilledOrderMetadataPatch } from '../utils/orderFulfilledMetadataEdit';
export { normalizeBackfillInvoiceStatus, planOrderInvoiceBackfill, buildBackfillInvoice, buildBackfillOrderPatch } from '../utils/orderInvoiceBackfill';
export { SALE_INVOICE_STATUSES, ACCOUNTING_INVOICE_STATUSES, normalizeInvoiceStatus, isSaleInvoiceStatus, isAccountingInvoiceStatus, assertSaleInvoiceStatus, canSaleTransitionInvoiceStatus, invoiceStatusChangeRequested, buildOrderInvoiceId, planOrderEditInvoiceMutation, validateAccountingInvoice } from '../utils/orderInvoiceFlow';
export { expandOrderItemLines, resolveOrderItemReference, collectOrderItemDependencies, validateOrderItemEdit, validateWarehouseReleaseSources } from '../utils/orderItemDependencies';
export { SAFE_RELATION_QUERY_CHUNK_SIZE, SAFE_NESTED_RELATION_QUERY_CHUNK_SIZE, uniqueOrderIds, chunkOrderIds, filterItemsForVisibleOrders, orderItemQueryKey } from '../utils/orderItemScope';
export { priceEditChanged, assertPriceOnlyItemChange, pricePatchForItem, priceOnlyItemsChanged } from '../utils/orderPriceEdit';
export { buildCommercialPrintHtml, buildDeliveryPrintHtml, openPrintDocument, CommercialPrintKind, PrintCustomer, DeliveryPrintRow } from '../utils/orderPrintDocuments';
export { ORDER_PRINTING_LOCK_VERSION, isActivePrintingProgress, activePrintingProgressForOrder, normalizedPrintingProgressCount, printingLockReady, printingDeleteBlocker, printingCountsByOrder, buildPrintingLockFields } from '../utils/orderPrintingDeleteLock';
export { ORDER_RELATION_LOCK_VERSION, DUPLICATE_ACTIVE_INVOICE_MESSAGE, RELATION_MODULES, isActiveOrderRelation, relationCountField, relationRevisionField, computePaymentRelationSummary, selectCanonicalInvoice, computeInvoiceRelationSummary, computeShipmentRelationSummary, computeRelationModuleSummary, replaceRelationRecord, removeRelationRecord, buildOrderRelationPatch, relationLockReady, orderRelationDeleteBlocker, relationRecordsByOrder, relationReconcileNeeded, buildReconciledOrderRelationPatch } from '../utils/orderRelationState';
export { warehouseRequestsForDeleteCascade, warehouseOrderDeleteBlocker } from '../utils/orderWarehouseDeleteLock';
export { buildParcelLabelPrintHtml, ParcelLabelType, ParcelLabelRow, ParcelLabelData } from '../utils/parcelLabelPrintDocuments';
export { PERMISSION_SCHEMA_VERSION, roleNamesFromUser, permissionList, roleMatchesName, auditPermissionAssignments, buildPermissionSyncPatch, summarizePermissionAudit } from '../utils/permissionAudit';
export { permissionDebug } from '../utils/permissionDebug';
export { moduleViewDecision, moduleActionDecision, exportRequestActionDecision, permissionDecisionMessage, DEFAULT_OWNER_FIELDS, ownsDocument, ownsLegacyOrderByUserCode } from '../utils/permissionDecisions';
export { PERMISSION_DENIED_USER_MESSAGE, normalizePermissionErrorEvent, subscribePermissionErrors, emitPermissionError, permissionDeniedUserMessage } from '../utils/permissionErrorBus';
export { QUERY_CACHE_SCHEMA_VERSION, QUERY_CACHE_STORAGE_PREFIX, stableSerialize, buildQueryCacheKey, createQueryCache } from '../utils/queryCache';
export { reconcileLegacyOrderForEdit, ReconcileLegacyOrderForEditResult } from '../utils/reconcileLegacyOrderForEdit';
export { REFERENCE_DATA_COLLECTIONS, REFERENCE_VERSION_QUERY_LIMIT, REFERENCE_VERSION_STORAGE_PREFIX, referenceSnapshotSignature, referenceVersionStorageKey, isReferenceDataCollection } from '../utils/referenceDataCache';
export { isHorizontallyOverflowing, visibleVerticalPixels, chooseStickyTableCandidate, stickyScrollbarBounds } from '../utils/stickyTableScrollbar';
export { toDateTimeMillis, isDateTimeInRange, buildWarehouseExportHistoryRows, matchesWarehouseExportHistoryFilters, uniqueHistoryOptions } from '../utils/warehouseExportHistory';
export { normalizeWarehouseLogo, inventoryBalanceId, sourceLogoOf, targetLogoOf, collectExportStockRequirements, buildStockShortageMessage, preflightExportStock } from '../utils/warehouseExportPreflight';
export { requestProductIdentityForLine, alignExportRequestLineProduct, alignExportRequestLineProducts } from '../utils/warehouseExportRequestIdentity';
export { externalExportManifestCountMatches, notificationDocumentId } from '../utils/warehouseExportSafety';
export { requestWarehouseItems, buildWarehouseFulfillmentRows, buildWarehouseOrderItemsFromRequestSnapshots, orderWarehouseFulfillmentSummaryFromRequests, orderWarehouseFulfillmentSummary, requestWarehouseLineProgress } from '../utils/warehouseFulfillment';
export { importUpdateTouchesInventory, importUpdateMode } from '../utils/warehouseImportUpdateMode';
export { expectedLifecycleForStatus, auditWarehouseLifecycle } from '../utils/warehouseLifecycleAudit';
export { canonicalWarehouseLogo, warehouseLogosEquivalent, warehouseLogoLookupVariants, equivalentWarehouseBalanceRows, selectEquivalentWarehouseBalance } from '../utils/warehouseLogoIdentity';
export { roundQuantity, sortInventoryLots, normalizeLots, reconcileOpeningLot, allocateInventoryLots, allocateManualInventoryLots, restoreInventoryLots, parseLotAllocations, WarehouseIssueStrategy, InventoryLotState, LotAllocation } from '../utils/warehouseLotAllocation';
export { useWarehouseTransactionsClient as useWarehouseTransactions } from '../composables/useWarehouseTransactionsClient';
export { useScopedQueriesClient as useScopedQueries } from '../composables/useScopedQueriesClient';